mozilla/marketplace-content-tools

src/js/actions/wizard.js
src/js/components/handlers/submission.js
src/js/components/wizard.js
src/js/flux.js
src/js/stores/wizard.js

Adds basic wizard functionality.

---

src/js/components/login.js
src/js/routes.js

Adds handler decorator to require login.

---

src/media/js/addon/actions/review.js
src/media/js/addon/components/addon.js
src/media/js/addon/containers/dashboard.js
src/media/js/addon/containers/review.js
src/media/js/addon/containers/reviewDetail.js

Adds reject action.

---

src/media/js/addon/actions/review.js
src/media/js/addon/components/addon.js
src/media/js/addon/containers/reviewDetail.js
src/media/js/addon/reducers/review.js

Disable the 'Publish' and 'Reject' buttons while the request is processing.

---

src/media/css/header.styl
src/media/css/pageheader.styl
src/media/js/addon/components/addonSubnav.js
src/media/js/addon/containers/dashboard.js
src/media/js/addon/containers/landing.js
src/media/js/addon/containers/review.js
src/media/js/addon/containers/reviewDetail.js
src/media/js/addon/containers/submit.js
src/media/js/site/components/header.js
src/media/js/site/components/pageHeader.js
src/media/js/site/components/subnav.js

Minor stuff, but I clearly paid deep attention to the aesthetics.
r? @ngokevin

Adds Subnav, PageHeader components, implements on add-ons pages.

---

src/media/js/addon/components/addon.js

Waiting on version fixes to the API to test.

[wip] Adds description to addon listing.

---

src/media/js/app.js
src/media/js/site/login.js

Require submission/review permissions to view respective parts of the content tools.

---

src/media/js/addon/actions/submit.js
src/media/js/addon/actions/submitVersion.js
src/media/js/addon/containers/dashboardDetail.js

I have absolutely no idea what I'm doing so I could be completely wrong but it seems to fix the issue for me (previously it would not show any errors when uploading a new version). I'd write tests but I can't run them: 
```
$ make test
(...)
/home/mat/work/mozilla/marketplace-content-tools/src/media/js/website/containers/__tests__/submit.test.js:10
jsdom();
^
ReferenceError: jsdom is not defined
at Suite.<anonymous> (/home/mat/work/mozilla/marketplace-content-tools/src/media/js/website/containers/__tests__/submit.test.js:10:3)
```

Fix errors not showing up during version upload

---

gulpfile.babel.js
package.json

Remove gulp-minify-css; it duplicates the work done by gulp-stylus.

---

src/media/js/addon/actions/dashboard.js
src/media/js/addon/actions/version.js
src/media/js/addon/components/version.js
src/media/js/addon/constants.js
src/media/js/addon/containers/__tests__/dashboardDetail.test.js
src/media/js/addon/containers/dashboardDetail.js
src/media/js/addon/containers/versionListing.js
src/media/js/addon/reducers/__tests__/addon.test.js
src/media/js/addon/reducers/addon.js
src/media/js/addon/reducers/dashboard.js
src/media/js/site/components/confirmButton.js

add-on deletion

---

src/media/js/addon/actions/review.js
src/media/js/addon/components/comm.js
src/media/js/addon/components/reviewActions.js
src/media/js/addon/components/version.js
src/media/js/site/components/confirmButton.js

allow reviewers to send message on review actions

---

src/media/css/buttons.styl
src/media/css/containers/index.styl
src/media/css/containers/tos.styl
src/media/css/page.styl
src/media/js/app.js
src/media/js/site/components/header.js
src/media/js/site/components/page.js
src/media/js/site/containers/app.js
src/media/js/site/containers/devAgreement.js
src/media/js/site/containers/tos.js
src/media/js/site/login.js

Style up the TOS-related things.

---

src/media/css/buttons.styl
src/media/css/containers/index.styl
src/media/css/containers/landing.styl
src/media/js/app.js
src/media/js/site/components/login.js
src/media/js/site/components/page.js
src/media/js/site/containers/__tests__/landing.test.js
src/media/js/site/containers/landing.js

r? @ngokevin 
The content in the UX doc ([page 10](https://drive.google.com/a/mozilla.com/file/d/0By5ZvBZQRgjRNW9Wek1HT3BDb1U/view)) was all FPO, so...everything is terrible. I'm asking around for somebody to write some real content. For now:

Pretty up the landing page.

---

src/media/css/containers/login.styl
src/media/js/site/containers/__tests__/landing.test.js
src/media/js/site/containers/__tests__/login.test.js
src/media/js/site/containers/landing.js
src/media/js/site/containers/login.js

Pretty up the login form.

---

src/media/css/buttons.styl
src/media/css/containers/addon-submit.styl
src/media/css/containers/addon-upload.styl
src/media/css/forms.styl
src/media/css/lib/colors.styl
src/media/css/lib/layout.styl
src/media/css/progressBar.styl
src/media/js/addon/components/progressBar.js
src/media/js/addon/components/upload.js
src/media/js/addon/containers/__tests__/submit.test.js
src/media/js/addon/containers/submit.js

r? @ngokevin 
This commit probably needs some cleanup itself, but I'm tired and want to get this out there tonight.
Video of it in action: http://chuck.mn/2N3K0j3D2P1O

Clean up the addon submission form.

---

src/media/css/base.styl
src/media/css/components/addon-listing-dashboard.styl
src/media/css/containers/addon-dashboard.styl
src/media/css/containers/addon-submit.styl
src/media/css/containers/landing.styl
src/media/css/lib/colors.styl
src/media/css/lib/layout.styl
src/media/js/addon/components/addon.js
src/media/js/addon/constants.js
src/media/js/addon/containers/__tests__/dashboard.test.js
src/media/js/addon/containers/dashboard.js

r? @ngokevin 
This page is pretty bad, getting a pass at it from Phil too, so the design isn't final.

Dashboard ux

---

src/media/js/addon/actions/addon.js
src/media/js/addon/actions/submitVersion.js
src/media/js/addon/components/install.js
src/media/js/addon/containers/reviewDetail.js
src/media/js/addon/reducers/addon.js

add-on install for reviewers

---

src/media/css/containers/landing.styl
src/media/css/lib/layout.styl
src/media/js/addon/components/upload.js
src/media/js/site/components/header.js
src/media/js/site/containers/landing.js

r? @ngokevin 
Includes a minor update to the layout of the landing page:

Makes content changes requested by the review team.

---

src/media/css/containers/login.styl
src/media/js/site/login.js

r? @ngokevin 
More helpful content for this is coming soon.

Slightly improved no permissions roadblock.

---

src/media/css/forms.styl
src/media/js/addon/components/upload.js
src/media/js/addon/components/validationError.js
src/media/js/addon/containers/__tests__/dashboardDetail.test.js
src/media/js/addon/containers/__tests__/submit.test.js
src/media/js/addon/containers/dashboardDetail.js
src/media/js/addon/containers/submit.js
src/media/js/addon/reducers/submit.js

Video: http://www.chuck.mn/0Q1s0V3w2u2x

Allow custom validation error messages per error key.

---

src/media/js/addon/components/upload.js
src/media/js/addon/components/validationError.js

Mo validation

---

src/media/js/addon/components/addonSubnav.js
src/media/js/addon/containers/__tests__/dashboard.test.js
src/media/js/addon/containers/__tests__/dashboardDetail.test.js
src/media/js/addon/containers/__tests__/review.test.js
src/media/js/addon/containers/__tests__/reviewDetail.test.js
src/media/js/addon/containers/__tests__/submit.test.js
src/media/js/addon/containers/dashboard.js
src/media/js/addon/containers/dashboardDetail.js
src/media/js/addon/containers/review.js
src/media/js/addon/containers/reviewDetail.js
src/media/js/addon/containers/submit.js
src/media/js/app.js
src/media/js/site/components/page.js
src/media/js/site/components/subnav.js
src/media/js/site/components/subnavItem.js
src/media/js/site/login.js

Hide subnav links behind permissions (bug 1212966).

---

src/media/js/site/containers/devAgreement.js

Updates developer agreement view to fetch the TOS URL from the server.

---

Makefile
src/media/css/base.styl
src/media/css/comm.styl
src/media/css/components/addon.styl
src/media/css/components/version.styl
src/media/css/containers/addon-dashboard-detail.styl
src/media/css/containers/addon-review.styl
src/media/css/forms.styl
src/media/js/__tests__/factory.test.js
src/media/js/addon/actions/addon.js
src/media/js/addon/actions/dashboard.js
src/media/js/addon/actions/review.js
src/media/js/addon/components/addon.js
src/media/js/addon/components/comm.js
src/media/js/addon/components/install.js
src/media/js/addon/components/listing.js
src/media/js/addon/components/version.js
src/media/js/addon/containers/dashboard.js
src/media/js/addon/containers/review.js
src/media/js/addon/containers/reviewDetail.js
src/media/js/site/components/page.js
src/media/js/site/login.js
webpack.config.js

incrementally make reviewer tools a little prettier

---

src/media/css/footer.styl
src/media/js/site/components/footer.js

Link Mozilla logo in footer (bug 1214108).

---

src/media/js/addon/components/version.js

Open version download links in the current window.

---

src/media/js/site/components/header.js
src/media/js/site/components/login.js
src/media/js/site/containers/login.js

FXA handles whether to show register vs. signin. We don't have control.

remove register btn (bug 1209530)

---

src/media/css/components/search.styl
src/media/css/containers/addon-review.styl
src/media/css/forms.styl
src/media/js/addon/actions/search.js
src/media/js/addon/components/search.js
src/media/js/addon/containers/review.js
src/media/js/addon/reducers/search.js
src/media/js/app.js

reviewer search

---

src/media/js/addon/components/addon.js

Remove mini-manifest link (bug 1205432).

---

package.json
src/media/css/components/slugChange.styl
src/media/css/forms.styl
src/media/js/addon/actions/addon.js
src/media/js/addon/components/slugChange.js
src/media/js/addon/containers/__tests__/dashboardDetail.test.js
src/media/js/addon/containers/dashboardDetail.js
src/media/js/addon/reducers/addon.js
src/media/js/site/containers/app.js

all hooked up, but API not working as expected. awaiting answers

allow dev to change slug

---

src/media/css/buttons.styl
src/media/css/containers/addon-dashboard-detail.styl
src/media/css/forms.styl

https://bugzilla.mozilla.org/show_bug.cgi?id=1218414

display issues for “Delete add-on” button label (bug 1218414)

---

src/media/css/components/reviewActions.styl

I had time, and it was easy. But I couldn't test it because I couldn't get login to work locally.

Move message on Publish so that it doesn't overlap the other buttons

---

src/media/js/addon/containers/dashboardDetail.js
src/media/js/site/components/confirmButton.js

disable delete addon button if blocked (bug 1240482)
